name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Package executable
      run: npx pkg .

    - name: Check version change
      id: check_version
      run: |
        git fetch --tags
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        if [ "v$CURRENT_VERSION" != "$LATEST_TAG" ]; then
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      if: steps.check_version.outputs.version_changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.check_version.outputs.new_version }}
        name: Release v${{ steps.check_version.outputs.new_version }}
        draft: false
        prerelease: false
        files: |
          freshslate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
